[package]
name = "lnd_grpc_rust"
version = "2.3.0"
authors = ["Martin Habovstiak <martin.habovstiak@gmail.com>", "Jonathan Zernik <yzernik@gmail.com>", "Nitesh Balusu <niteshbalusu@icloud.com>"]
edition = "2018"
description = "An async library implementing LND RPC via tonic_openssl and prost"
homepage = "https://github.com/niteshbalusu11/lnd-grpc-rust"
repository = "https://github.com/niteshbalusu11/lnd-grpc-rust"
readme = "README.md"
keywords = ["LND", "rpc", "grpc", "tonic", "async"]
categories = ["api-bindings", "asynchronous", "cryptography::cryptocurrencies", "network-programming"]
license = "MIT"

[lib]
doctest = false

[dependencies]
tonic = "0.7"
tonic-openssl = { version = "0.2" }
hyper = "0.14"
hyper-openssl = "0.9"
prost = "0.10"
tokio = { version = "1.35", features = ["rt-multi-thread", "macros"] }
tokio-stream = { version = "0.1.14", features = ["net"] }
openssl = "0.10.16"
tower = "0.4.13"
pretty_env_logger = "0.5.0"
hex = "0.4.3"

[build-dependencies]
tonic-build = "0.7"
